CREATE DATABASE IF NOT EXISTS rishtewale CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rishtewale;
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(80) PRIMARY KEY, `value` TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, gender ENUM('male','female') NOT NULL, age INT NOT NULL, name VARCHAR(100) NOT NULL, state VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, whatsapp VARCHAR(30) NOT NULL, telegram VARCHAR(100) DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS profiles (id INT AUTO_INCREMENT PRIMARY KEY, gender ENUM('male','female') NOT NULL, name VARCHAR(100), age INT, state VARCHAR(100), city VARCHAR(100), photo VARCHAR(255), about TEXT, marital_status VARCHAR(80), annual_income VARCHAR(80), description TEXT, caste VARCHAR(100), religion VARCHAR(100), whatsapp VARCHAR(30), active TINYINT DEFAULT 1, featured TINYINT DEFAULT 0, online TINYINT DEFAULT 1);
CREATE TABLE IF NOT EXISTS premium_orders (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,amount DECIMAL(10,2),utr VARCHAR(100),status ENUM('pending','approved','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS earning_applications (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,age INT,hours VARCHAR(100),time_slot VARCHAR(100),phone VARCHAR(30),telegram VARCHAR(100),city VARCHAR(100),status ENUM('pending','contacted','approved','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT IGNORE INTO settings VALUES
('site_name','Rishtewale'),('tagline','Apna behtareen rishta dhoondhiye'),('male_premium_price','199'),('female_premium_price','99'),('upi_id','dilseconnect@upi'),('qr_image',''),('telegram_bot_token',''),('telegram_chat_id',''),('phonepe','1'),('gpay','1'),('paytm','1'),('home_heading','Apna behtareen rishta dhoondhiye'),('home_subtitle','Verified demo profiles • Safe & simple registration'),('home_online_count','24+'),('home_note','✨ Aaj naye profiles online hain — register karke matches dekhein'),('home_profile_1_name','Priya'),('home_profile_1_city','Lucknow'),('home_profile_2_name','Neha'),('home_profile_2_city','Kanpur'),('home_profile_3_name','Pooja'),('home_profile_3_city','Delhi'),('home_profile_4_name','Riya'),('home_profile_4_city','Jaipur'),('home_profile_5_name','Anjali'),('home_profile_5_city','Mahoba'),('home_profile_6_name','Simran'),('home_profile_6_city','Agra'),('female_banner_title','स्वागत है'),('female_banner_subtitle','आपका रजिस्ट्रेशन सफलतापूर्वक हो गया है।'),('female_banner_image','https://randomuser.me/api/portraits/women/44.jpg'),('female_earning_title','Hamare Sath Judkar'),('female_earning_subtitle','30 min Video Calling करके Extra Earning करें');
